version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - bookingroom-network

  webserver:
    image: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bookingroom-network

  mysql:
    image: mysql:8.2.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bookingroom_password
      MYSQL_DATABASE: bookingroom_db
      MYSQL_USER: bookingroom_user
      MYSQL_PASSWORD: bookingroom_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - bookingroom-network

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - "8888:80"
    depends_on:
      - mysql
    networks:
      - bookingroom-network

volumes:
  dbdata:
    driver: local

networks:
  bookingroom-network:
    driver: bridge